[package]
name = "budokan_prize"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
openzeppelin_interfaces.workspace = true
budokan_interfaces = { path = "../interfaces" }
budokan_token_validator = { path = "../token_validator" }

[dev-dependencies]
snforge_std.workspace = true
