[world]
name = "Budokan Event Relayer"
description = "Event relayer for Budokan tournaments"
seed = "budokan_event_relayer"

[env]
rpc_url = "http://localhost:5050"

[namespace]
default = "budokan_relayer_0_0_1"

[writers]
"budokan_relayer_0_0_1" = [
    "budokan_relayer_0_0_1-BudokanEventRelayer",
]
