[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"
world_address = "0x02ef591697f0fd9adc0ba9dbe0ca04dabad80cf95f08ba02e435d9cb6698a28a"

[namespace]
default = "budokan_relayer_0_0_1"

[writers]
"budokan_relayer_0_0_1" = [
    "budokan_relayer_0_0_1-BudokanEventRelayer",
]
