[world]
name = "Budokan Event Relayer"
description = "Event relayer for Budokan tournaments"
seed = "budokan_event_relayer"

[env]
rpc_url = "http://localhost:5050"

[namespace]
default = "budokan_relayer_0_0_1"

[writers]
"budokan_relayer_0_0_1" = [
    "budokan_relayer_0_0_1-BudokanEventRelayer",
]

[init_call_args]
"budokan_relayer_0_0_1-BudokanEventRelayer" = [
    "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # katana default deployer
]
