[package]
name = "budokan_event_relayer"
version = "0.0.1"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.8.0" }
openzeppelin_access = "1.0.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.10.1"

[lib]

[profile.dev]
[profile.sepolia]
[profile.mainnet]
