[package]
name = "budokan_event_relayer"
version.workspace = true
edition.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
openzeppelin_access.workspace = true
budokan = { path = "../budokan" }

[dev-dependencies]
snforge_std.workspace = true
