[package]
name = "budokan"
version.workspace = true
edition.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "game_components_test_starknet::minigame::mocks::minigame_starknet_mock::minigame_starknet_mock",
    "game_components_test_starknet::metagame::mocks::metagame_starknet_mock::metagame_starknet_mock",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
openzeppelin_access.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_upgrades.workspace = true
game_components_metagame.workspace = true
game_components_minigame.workspace = true
game_components_utils.workspace = true
game_components_test_starknet.workspace = true
game_components_token.workspace = true
game_components_leaderboard.workspace = true
budokan_distribution = { path = "../distribution" }
budokan_interfaces = { path = "../interfaces" }
budokan_entry_fee = { path = "../entry_fee" }
budokan_entry_requirement = { path = "../entry_requirement" }
budokan_prize = { path = "../prize" }
budokan_registration = { path = "../registration" }
beacon_entity = { git = "https://github.com/sai-starknet/torii-beacon", tag = "v1.7.3" }
beacon_macros = { git = "https://github.com/sai-starknet/torii-beacon", tag = "v1.7.3" }
beacon_library = { git = "https://github.com/sai-starknet/torii-beacon", tag = "v1.7.3" }

[dev-dependencies]
cairo_test = "2.13.1"
snforge_std.workspace = true

[features]
default = []
