[package]
name = "budokan_entry_requirement"
version.workspace = true
edition.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[target.starknet-contract.contracts]
budokan_extensions_open_entry_validator_mock = "budokan_entry_requirement::tests::mocks::open_entry_validator_mock::open_entry_validator_mock"
budokan_extensions_SnapshotValidator = "budokan_entry_requirement::examples::snapshot_validator::SnapshotValidator"
budokan_extensions_TournamentValidator = "budokan_entry_requirement::examples::tournament_validator::TournamentValidator"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_introspection.workspace = true
budokan_interfaces = { path = "../interfaces" }
game_components_minigame.workspace = true

[dev-dependencies]
snforge_std.workspace = true
openzeppelin_token.workspace = true

[tool.snforge]
[[tool.snforge.fork]]
name = "sepolia"
url = "https://api.cartridge.gg/x/starknet/sepolia"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "mainnet"
url = "https://api.cartridge.gg/x/starknet/mainnet"
block_id.tag = "latest"
