[workspace]
members = [
    "packages/math",
    "packages/distribution",
    "packages/interfaces",
    "packages/entry_fee",
    "packages/entry_requirement",
    "packages/prize",
    "packages/registration",
    "packages/budokan",
]

[workspace.package]
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.13.1"

[workspace.dependencies]
starknet = "2.13.1"
cairo_test = "2.13.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.53.0" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.8.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
game_components_metagame = { path = "../../game-components/packages/metagame" }
game_components_minigame = { path = "../../game-components/packages/minigame" }
game_components_utils = { path = "../../game-components/packages/utils" }
game_components_test_starknet = { path = "../../game-components/packages/test_starknet" }
game_components_token = { path = "../../game-components/packages/token" }
game_components_leaderboard = { path = "../../game-components/packages/leaderboard" }

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]
