name: test-contracts

env:
  SCARB_VERSION: 2.13.1

on:
  pull_request:
    paths-ignore:
      - "ui/**"
      - "**/manifest.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scarb-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Run Scarb Build
        run: |
          cd contracts && scarb build
      - name: Run Tests
        run: |
          cd contracts && scarb test

  scarb-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - run: cd contracts && scarb fmt --check
