[package]
name = "budokan_interfaces"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
budokan = { path = "../budokan" }
budokan_distribution = { path = "../distribution" }
budokan_registration = { path = "../registration" }
budokan_entry_fee = { path = "../entry_fee" }
budokan_entry_requirement = { path = "../entry_requirement" }
budokan_token_validator = { path = "../token_validator" }
budokan_prize = { path = "../prize" }

[dev-dependencies]
snforge_std.workspace = true
